# Generated by Django 4.2 on 2023-04-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('Rain', 'Rain'), ('Snow', 'Snow'), ('Fog', 'Fog'), ('Other', 'Other')], max_length=10)),
                ('outdoor_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ground_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('other_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('LIDAR', 'Lidar'), ('TOF', 'Tof Camera'), ('VISUAL', 'Visual Camera'), ('OTHERS', 'Others'), ('LEGACY', 'Legacy')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
